package com.a21230528.chess.Logic;

/**
 * Created by rafaelfrancisco on 29/12/17.
 */

public enum Piece {
    PAWN_WHITE, PAWN_BLACK, ROOK_WHITE, ROOK_BLACK, QUEEN_WHITE, QUEEN_BLACK, KING_WHITE, KING_BLACK, KNIGHT_WHITE, KNIGHT_BLACK, BISHOP_WHITE, BISHOP_BLACK, EMPTY
}